applications:
- api_domain: grocerybarcodescanner.onrender.com
  application_name: barcode
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://grocerybarcodescanner.onrender.com
  type: web
